name       : leptonica
version    : '1.78.0'
release    : 7
source     :
    - https://github.com/DanBloomberg/leptonica/archive/1.78.0.tar.gz : f8ac4d93cc76b524c2c81d27850bfc342e68b91368aa7a1f7d69e34ce13adbb4
license    : BSD-2-Clause
component  : programming.library
summary    : Leptonica image processing and analysis
description: |
    Leptonica image processing and analysis
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - gnuplot # check
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
