name       : leptonica
version    : 1.73
release    : 3
source     :
    - https://github.com/DanBloomberg/leptonica/archive/v1.73.tar.gz : f5669ce2e30f873833474df005f606e96bdcaa9aa43aead21b6709ecaec1fc05
license    : BSD-2-Clause
component  : programming
summary    : Leptonica image processing and analysis
description: |
    Leptonica image processing and analysis
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - libjpeg-turbo-devel
setup      : |
    rm configure
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
