name       : leptonica
version    : 1.83.1
release    : 13
source     :
    - https://github.com/DanBloomberg/leptonica/archive/refs/tags/1.83.1.tar.gz : 4289d0a4224b614010072253531c0455a33a4d7c7a0017fe7825ed382290c0da
homepage   : http://www.leptonica.org/
license    : BSD-2-Clause
component  : programming.library
summary    : Leptonica image processing and analysis
description: |
    Leptonica is a pedagogically-oriented open source library containing software that is broadly useful for image processing and image analysis applications.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libwebp)
    - gnuplot # check
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check ||:
